name: dart_mars
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/tangpanqing/dart_mars

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  process_run: ^0.12.1
  buffer: ^1.1.1
  yaml: ^3.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
